  
export const HEROSPARAM = [
    {
        id: 1,
        life: 100,
        power: 15,
        attaqueSpeciale: 8,
        name: "Arkan",
        picture: "../assets/joueur_musique_rouge.jpg",
        type: "feu",
    },
    {
        id: 2,
        life: 120,
        power:15,
        name: "Lyra",
        attaqueSpeciale: 6,
        picture: "../assets/homme_pistolet_bleu.jpg",
        type: "eau",
    },
    {
        id: 3,
        name: "Aiden",
        life: 80,
        power: 15,
        attaqueSpeciale: 12,
        picture: "../assets/femme_pistolet_rouge.jpg",
        type: "feu",
    },
    {
        id: 4,
        name: "Elara",
        life: 150,
        power: 15,
        attaqueSpeciale: 1,
        picture: "../assets/pretre_bleu.jpg",
        type: "eau",
    },
    {
        id: 5,
        name: "Magnus",
        life: 110,
        power: 15,
        attaqueSpeciale: 9,
        picture: "../assets/pretre_rouge.jpg",
        type: "feu",
    },
    {
        id: 6,
        name: "Seraphina",
        life: 110,
        power:15,
        attaqueSpeciale: 9,
        picture: "../assets/femme_verte_arc.jpg",
        type: "plante",
    },
    {
        id: 7,
        name: "Draven",
        life: 130,
        power: 15,
        attaqueSpeciale: 6,
        picture: "../assets/zombie_vert.jpg",
        type: "feu",
    },
    {
        id: 8,
        name: "Freya",
        life: 70,
        power: 15,
        attaqueSpeciale: 14,
        picture: "../assets/guerriere_hache_marteau.jpg",
        type: "plante",
    },
    {
        id: 9,
        name: "Orion",
        life: 118,
        power: 15,
        attaqueSpeciale: 6,
        picture: "../assets/guerrier_hache_marteau.jpg",
        type: "plante",
    },
    {
        id: 10,
        name: "Lumiya",
        life: 120,
        power: 15,
        attaqueSpeciale: 5,
        picture: "../assets/femme_brun_epee.jpg",
        type: "eau",
    },
    {
        id: 11,
        name: "Xander",
        life: 100,
        power: 15,
        attaqueSpeciale: 8,
        picture: "../assets/bonhomme_vert_pretre.jpg",
        type: "plante",
    },
    {
        id: 12,
        name: "Nova",
        life: 140,
        power: 15,
        attaqueSpeciale: 2,
        picture: "../assets/bonhomme_gris_epee.jpg",
        type: "eau",
    }
];